
name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1

      - name: Install metadata validator dependencies
        run: |
          wget https://github.com/unicode-org/icu/releases/download/release-71-1/icu4c-71_1-Ubuntu20.04-x64.tgz
          tar -xf icu4c-71_1-Ubuntu20.04-x64.tgz

          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ github.workspace }}/icu/usr/local/lib" >> "$GITHUB_ENV"

      - name: Install metadata validator
        run: wget https://github.com/loot/metadata-validator/releases/download/0.21.0/metadata-validator-0.21.0-0-gd56177b_0.21.0-Linux.tar.xz -O - | tar -xJ --strip-components=1

      - name: Install parser
        run: npm install -g js-yaml

      - name: Download prelude file
        run: wget https://raw.githubusercontent.com/loot/prelude/v0.21/prelude.yaml

      - name: Run metadata validator
        run: |
          ./metadata_validator $GITHUB_WORKSPACE/masterlist.yaml
          ./metadata_validator $GITHUB_WORKSPACE/masterlist.yaml $GITHUB_WORKSPACE/prelude.yaml
          js-yaml $GITHUB_WORKSPACE/masterlist.yaml > /dev/null
